# Use the acc-py-devtools templates found at
# https://gitlab.cern.ch/-/ide/project/acc-co/devops/python/acc-py-devtools/blob/master/-/acc_py_devtools/templates/gitlab-ci/python.yml.
include:
 - project: acc-co/devops/python/acc-py-devtools
   file: acc_py_devtools/templates/gitlab-ci/python.yml

variables:
  project_name: pyda_japc
  PY_VERSION: '3.7'

  ACCSOFT_DS_MODEL_REPO:
    value: "acc-co/devops/python/prototypes/accsoft-ds-model-py"
    description: "The repo project name for pyds-model"

  ACCSOFT_DS_MODEL_REF:
    value: "master"
    description: "The ref to use from $ACCSOFT_DS_MODEL_REPO to test against."

  PYDA_CORE_REPO:
    value: "acc-co/devops/python/prototypes/pyda"
    description: "The repo project name for the core pyda library"

  PYDA_CORE_REF:
    value: "master"
    description: "The ref to use from PYDA_CORE_REPO to test against."


# A development installation of pyda-japc tested with pytest.
test_dev:
  extends: .acc_py_dev_test
  stage: test
  image: registry.cern.ch/acc/acc-py_cc7_openjdk11_ci:2020.11
  before_script:
    # Find the suitable wheel provided in the wheelhouse directory, and put it in a ./wheel-to-install directory.
    - python -m pip wheel --no-deps --no-index --find-links ./wheelhouse --wheel-dir ./wheels-to-install
        pyda pyds-model
    # Install the wheel that was found (and all dependencies via the package index),
    # this project (with test dependencies) and coverage functionality.
    # Doing this as a single install command will ensure that if the project pins
    # versions which are incompatible with the upstream versions, the command will fail.
    - python -m pip install
        ./wheels-to-install/*.whl
        -e .[test]
        pytest-cov
  needs:
    - project: "${ACCSOFT_DS_MODEL_REPO}"
      job: build_wheel
      ref: "${ACCSOFT_DS_MODEL_REF}"
      artifacts: true
    - project: "${PYDA_CORE_REPO}"
      job: build_wheel
      ref: "${PYDA_CORE_REF}"
      artifacts: true


# A push of the source distribution to the acc-py PyPI, only on git tag.
release_sdist_on_tag:
  extends: .acc_py_release_sdist
